export const abi = [
  {
    type: "function",
    name: "getAllReviewsFromSponsor",
    inputs: [{ name: "_sponsor", type: "string", internalType: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct PayMePrettyPlease.Review[]",
        components: [
          { name: "sponsor", type: "string", internalType: "string" },
          { name: "rating", type: "uint8", internalType: "uint8" },
          { name: "comment", type: "string", internalType: "string" },
          {
            name: "evidenceHashes",
            type: "string[]",
            internalType: "string[]",
          },
          { name: "prizeAmount", type: "uint256", internalType: "uint256" },
          { name: "prizePaidOut", type: "bool", internalType: "bool" },
          {
            name: "hackathonEndDate",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "payoutDate", type: "uint256", internalType: "uint256" },
          { name: "reviewer", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrganization",
    inputs: [{ name: "_sponsor", type: "string", internalType: "string" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "avgPayoutTime", type: "uint256", internalType: "uint256" },
      { name: "rating", type: "uint256", internalType: "uint256" },
      { name: "totalReviews", type: "uint256", internalType: "uint256" },
      { name: "lastReviewTimestamp", type: "uint256", internalType: "uint256" },
      { name: "pendingPayouts", type: "uint256", internalType: "uint256" },
      { name: "paidOutReviews", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReview",
    inputs: [{ name: "_reviewId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PayMePrettyPlease.Review",
        components: [
          { name: "sponsor", type: "string", internalType: "string" },
          { name: "rating", type: "uint8", internalType: "uint8" },
          { name: "comment", type: "string", internalType: "string" },
          {
            name: "evidenceHashes",
            type: "string[]",
            internalType: "string[]",
          },
          { name: "prizeAmount", type: "uint256", internalType: "uint256" },
          { name: "prizePaidOut", type: "bool", internalType: "bool" },
          {
            name: "hackathonEndDate",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "payoutDate", type: "uint256", internalType: "uint256" },
          { name: "reviewer", type: "address", internalType: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getReviewsBySponsor",
    inputs: [{ name: "_sponsor", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markPrizePaidOut",
    inputs: [{ name: "_reviewId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "organizations",
    inputs: [{ name: "", type: "string", internalType: "string" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "totalPayoutTime", type: "uint256", internalType: "uint256" },
      { name: "totalReviews", type: "uint256", internalType: "uint256" },
      { name: "totalRating", type: "uint256", internalType: "uint256" },
      { name: "lastReviewTimestamp", type: "uint256", internalType: "uint256" },
      { name: "pendingPayouts", type: "uint256", internalType: "uint256" },
      { name: "paidOutReviews", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reviewCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reviews",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "sponsor", type: "string", internalType: "string" },
      { name: "rating", type: "uint8", internalType: "uint8" },
      { name: "comment", type: "string", internalType: "string" },
      { name: "prizeAmount", type: "uint256", internalType: "uint256" },
      { name: "prizePaidOut", type: "bool", internalType: "bool" },
      { name: "hackathonEndDate", type: "uint256", internalType: "uint256" },
      { name: "payoutDate", type: "uint256", internalType: "uint256" },
      { name: "reviewer", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submitReview",
    inputs: [
      { name: "_sponsor", type: "string", internalType: "string" },
      { name: "_rating", type: "uint8", internalType: "uint8" },
      { name: "_comment", type: "string", internalType: "string" },
      { name: "_evidenceHashes", type: "string[]", internalType: "string[]" },
      { name: "_prizeAmount", type: "uint256", internalType: "uint256" },
      { name: "_hackathonEndDate", type: "uint256", internalType: "uint256" },
      { name: "_isAlreadyPaidOut", type: "bool", internalType: "bool" },
      { name: "_payoutDate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "PrizePaidOut",
    inputs: [
      {
        name: "reviewId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "sponsor",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "payoutTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReviewSubmitted",
    inputs: [
      {
        name: "reviewId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "reviewer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sponsor",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
] as const;
